server:
  port: 10100 # 8080
  contextPath: /xapi
  
spring:
#  cloud:     config:       uri: http://localhost:8888/
  jackson:
    serialization.fail-on-empty-beans: false  
account:
  protocol: "http://"
  domain: "ec2-35-177-112-78.eu-west-2.compute.amazonaws.com" # localhost:10001 ec2-52-56-203-3.eu-west-2.compute.amazonaws.com
  path: "/ipay/account/"
  

